"""empty message

Revision ID: 979bfdeae6a8
Revises: 
Create Date: 2021-05-21 13:03:40.462464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979bfdeae6a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('create_data', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('create_data', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['todolist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('todolist')
    # ### end Alembic commands ###
